### ISSUE TITLE
Possible github release

### ISSUE THREAD

**Issue by qbouvet** [KVAnton-WEB/Checksum-Blister#2]
Hi, I'd like to create an AUR package for your extension. It allows arch linux users to easily it direcly via their package manager instead of the KDE store.

For technical reasons I find it slightly cleaner to write the package against a git release rather than picking the current latest commit number. Could you consider creating a git release ? 

Best regards,

Quentin

**Comment by KVAnton-WEB** [comment]
https://github.com/KVAnton-WEB/Checksum-Blister/releases

like this?

**Comment by ghost** [comment]
yep great, thanks !
